id: IB98A9FE9
ocr_import_info:
  timestamp: '2023-08-21T07:20:12.630840+00:00'
  batch_id: batch-d48c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-21 08:39:27.147795+00:00
last_modified: 2023-08-21 08:39:27.147804+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W24052
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24052
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཉི་མ།
  languages:
  - bo
  author: ངག་དབང་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.983008876467753
  ocr_word_median_confidence_index: 0.9999993
bases:
  I3824:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3824
      total_pages: 548
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3824.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999992
      ocr_word_mean_confidence_index: 0.9834430318085662
  I3823:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3823
      total_pages: 812
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3823.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999998
      ocr_word_mean_confidence_index: 0.9839239005083207
  I3821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3821
      total_pages: 654
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3821.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999998
      ocr_word_mean_confidence_index: 0.9856494689808768
  I3826:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3826
      total_pages: 700
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3826.txt
    statistics:
      ocr_word_median_confidence_index: 0.99998033
      ocr_word_mean_confidence_index: 0.9759090114542073
  I3825:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3825
      total_pages: 686
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3825.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999994
      ocr_word_mean_confidence_index: 0.9849377490250244
  I3822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3822
      total_pages: 548
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3822.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999992
      ocr_word_mean_confidence_index: 0.9839782182578644
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
